name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # メインブランチにプッシュされた時に実行

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-northeast1  # 東京リージョン
  SERVICE_NAME: hoken-talk-search  # Cloud Runのサービス名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 'Login to Artifact Registry'
      uses: 'docker/login-action@v3'
      with:
        registry: asia-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and Push Container
      run: |-
        docker build -t asia-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }} .
        docker push asia-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image asia-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }} \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets="OPENAI_API_KEY=OPENAI_API_KEY:latest" \
          --set-secrets="GOOGLE_API_KEY=GOOGLE_API_KEY:latest" \
          --set-secrets="GOOGLE_CSE_ID=GOOGLE_CSE_ID:latest" \
          --set-secrets="BING_API_KEY=BING_API_KEY:latest"